name: pappes_web_utility
version: 1.0.1
description: A library useful for web applications.  Currently includes MyHtml which is a class with HTML helper functions and MyJS which is a class with JavaScript helper functions
homepage: https://github.com/pappes/aarvark
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  #browser: '>=0.10.0 <0.11.0'
  logging: ^1.0.2
  pappes_utility: ^1.0.3
  js: ^0.6.4
  intl: ^0.17.0
  #universal_html: ^2.0.8

dev_dependencies:
  lints: ^1.0.1
  test: ^1.20.2
